Projekt Python Flask Piotr Otta/aplikacjaflask/__init__.py
import os

from flask import Flask


def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY="administrator-piotr",
        DATABASE=os.path.join(app.instance_path, "baza_danych.sqlite"),
    )

    if test_config is None:
        app.config.from_pyfile("config.py", silent=True)
    else:
        app.config.update(test_config)
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from aplikacjaflask import db

    db.init_app(app)

    from aplikacjaflask import logowanie, posty, routes

    app.register_blueprint(routes.bp)
    app.register_blueprint(logowanie.bp)
    app.register_blueprint(posty.bp)

    app.add_url_rule("/", endpoint="index")

    return app

Projekt Python Flask Piotr Otta/aplikacjaflask/routes.py
from flask import Blueprint
from flask import render_template

bp = Blueprint("home", __name__)


@bp.route("/")
def index():
    return render_template("home/index.html")

@bp.route("/about")
def omnie():
    return render_template("home/o_mnie.html")

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/blog/create.html
{% extends 'schemat.html' %}

{% block header %}
  <h1>{% block title %}Tworzenie nowego postu{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
      <div class="form-group">
          <label for="title">Tytuł</label>
          <input name="title" class="form-control" id="title" value="{{ request.form['title'] }}" required>
      </div>
      <div class="form-group">
          <label for="body">Treść</label>
          <textarea name="body" class="form-control" id="body">{{ request.form['body'] }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">Zapisz</button>
      <br>
          <div class="row">
            <div class="col">
            </div>
            <div class="col">
              <a href="/blog"><button type="button" class="btn btn-warning btn-block">
            Anuluj
          </button></a>
            </div>
          </div>
  </form>
{% endblock %}

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/blog/index.html
{% extends 'schemat.html' %}

{% block header %}
  <h1 class="text-center" id="posty">{% block title %}Posty{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('blog.create') }}">
        <button type="button" class="btn btn-outline-primary">Utwórz nowy</button>
    </a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post shadow-sm p-3 mb-3 bg-white rounded">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">przez: {{ post['username'] }}<br>  dnia: {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action badge badge-pill badge-info" href="{{ url_for('blog.update', id=post['id']) }}">Edytuj</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
    {% endif %}
  {% endfor %}
{% endblock %}

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/blog/update.html
{% extends 'schemat.html' %}

{% block header %}
  <h2>{% block title %}Edycja "{{ post['title'] }}"{% endblock %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
      <div class="form-group">
          <label for="title">Tytuł</label>
          <input name="title" class="form-control" id="title" value="{{ request.form['title'] or post['title'] }}" required>
      </div>
      <div class="form-group">
          <label for="body">Treść</label>
          <textarea name="body" class="form-control" id="body">{{ request.form['body'] or post['body'] }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
  </form>
  <form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
      <div class="container">
          <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-danger btn-block">Usuń</button>
            </div>
            <div class="col">
                <a href="/blog"><button type="button" class="btn btn-warning btn-block">
                Anuluj
                </button></a>
            </div>
          </div>
      </div>
  </form>
{% endblock %}

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/home/index.html
{% extends 'schemat.html' %}

{% block header %}
{% endblock %}
{% block content %}
<style>
    .content {
        background-color: rgba(0, 255, 255, 0);
    }
</style>
  <div id="header_container" class="text-center">
            <div id="header_logo">
                <div id="scene" class="scene">
                    <div data-depth="0.60">
                        <img  class="img-fluid"src="../../static/assets/Logo%20Codilion%20No%20BG%20-White.png">
                    </div>
                </div>
            </div>
            <div id="header_text">
                <h1 class="text-white m-3">Projekt python + Flask</h1>
                <h3>Wykonany przez Piotra Otta</h3>
            </div>
        </div>
<script src="../../static/js/parallax.min.js"></script>
<script>
	var scene = document.getElementById('scene');
	var parallax = new Parallax(scene);
</script>
{% endblock %}

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/home/o_mnie.html
{% extends 'schemat.html' %}

{% block header %}
  <h2 class="display-4">{% block title %}O mnie{% endblock %}</h2>
{% endblock %}

{% block content %}
<p class="lead">Witryna stworzona przez Piotra Otta 18902,
<br>
    studia stacjonarne, inżynierskie, rok II, kierunek informatyka.
</p>
<style>
    h2, p {
        background:-webkit-gradient(linear,left top,right bottom,from(rgba(79, 116, 219, 0.9)),to(rgba(88, 207, 217, 0.9)));
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
    .content {
        background-color: rgb(255, 255, 255);
    }
</style>
{% endblock %}

Projekt Python Flask Piotr Otta/aplikacjaflask/templates/schemat.html
<!doctype html>
<head>
    <title>{% block title %}Strona główna{% endblock %} - Piotr Otta</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <meta name="description" content="Projekt python - FLASK">
    <meta name="author" content="PiotrOtta">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="{{ url_for('static', filename='assets/ikona.png') }} ">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <header class="header">
        <nav class="navbar d-flex flex-row-reverse">
        <ul class="navbar-nav list-group-horizontal ">
            {% if g.user %}
            <li class="nav-item">
            <span class="badge badge-pill badge-primary">Zalogowano jako: {{ g.user['username'] }}</span>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('auth.logout') }}">Wyloguj się</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{{ url_for('auth.login') }}">Zaloguj się</a>
            </li>
            {% endif %}
        </ul>
    </nav>
        <nav class="navbar justify-content-center">
            <ul class="navbar-nav list-group-horizontal ">
                    <li class="nav-item">
                        <a href="{{ url_for('index') }}">GŁÓWNA</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('home.omnie') }}">O MNIE</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('blog.index') }}">BLOG</a>
                    </li>
            </ul>
        </nav>
    </header>
    <div class="d-flex justify-content-center">
        <section class="content">
        <h3>
        {% block header %}{% endblock %}
        </h3>
            
        {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
        </section>
    </div>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>